{{- $name := (include "sidecar-injector.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
{{- $component := "sidecar-injector" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    appProtocol: https
    targetPort: https
    {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
