{{- $name := (include "sidecar-injector.name" $) }}
{{- $namespace := (include "kyverno.lib.namespace" $) }}
{{- $component := "sidecar-injector" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kyverno.lib.labels.merge" (list
      (include "kyverno.lib.labels.common" $)
      (include "kyverno.lib.labels.common.selector" $)
      (include "kyverno.lib.labels.component" $component)
    ) | nindent 4 }}
data:
  sidecar.yaml: |
    {{- with .Values.sidecar.containers }}
    # containers
    containers:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.sidecar.initContainers }}
    # initContainers
    initContainers:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.sidecar.volumes }}
    # volumes
    volumes:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
    {{- with .Values.sidecar.imagePullSecrets }}
    # image pull secrets
    imagePullSecrets:
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
